# Instead of deleting and recreating tehe build directory again and again 
# Write the command sequence as below 
# run the command # make 
# or # make prepare
prepare:
	rm -rf build
	mkdir build 
# Can be automated the CMake configuration generation and make build process
# generate_config:
# 	cmake -S . -B ./build 
# 	cmake --build ./build
